[platformio]
default_envs = native


; PC Simulator
[env:native]
platform = native
build_type = debug
build_flags =
    -std=gnu++17
    -DSIMULATION

; Arduino Uno (Real Hardware)
[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags =
    -DARDUINO_BUILD
